"""Visual EMA defaults; distances are screenshot pixels, not price units."""

EMA_ANALYSIS_ENABLED = True
EMA_ENTRY_FILTER_ENABLED = True
DEBUG_MODE = True
EMA_FAST_PERIOD = 9
EMA_SLOW_PERIOD = 21
# OpenCV hue is 0..179. Exclude green candles, red expiration and dark grid.
EMA_FAST_HSV_LOW = (85, 140, 140)
EMA_FAST_HSV_HIGH = (115, 255, 255)
EMA_SLOW_HSV_LOW = (10, 140, 140)
EMA_SLOW_HSV_HIGH = (38, 255, 255)
EMA_MIN_POINTS = 80
EMA_MIN_SEGMENT_WIDTH = 20
EMA_MAX_LINE_THICKNESS_PX = 6
# Measured cyan mask gap: 14px native, 25px at 1.5x after HSV filtering.
EMA_MAX_GAP_PX = 28
EMA_MAX_STEP_SLOPE = 2.0
EMA_SLOPE_LOOKBACK = 100
EMA_SLOPE_FLAT_MARGIN = 0.03
# Initial visual thresholds for the supplied 1000x289 crop; recalibrate for zoom.
EMA_CLOSE_DISTANCE_PX = 4.0
EMA_SEPARATED_DISTANCE_PX = 12.0
EMA_RELATION_MARGIN_PX = 2.0
EMA_DISTANCE_CHANGE_MARGIN_PX = 1.0
EMA_TRACK_RADIUS_PX = 12
EMA_RECOVERY_RADIUS_PX = 36
EMA_RECALIBRATION_FRAMES = 3
EMA_MAX_FRAME_GAP_SECONDS = 1.0
EMA_CROSS_CONFIRMATION_FRAMES = 3
EMA_MIN_CONFIDENCE = 75.0
EMA_CONFIDENCE_WEIGHTS = (0.20, 0.25, 0.20, 0.15, 0.20)
